CREATE TABLE PARTICIPANT (
    ID_PART INT,
    NOM VARCHAR(255),
    PRENOM VARCHAR(255),
    DATENAISS DATE,
    NATIONALITE VARCHAR(255),
    CONSTRAINT PK_PARTICIPANT PRIMARY KEY (ID_PART)
);

CREATE TABLE COMITE (
    ID_MEMBRE INT,
    MOT_DE_PASSE VARCHAR(32),
    ID_PART INT,
    CONSTRAINT PK_COMITE PRIMARY KEY (ID_MEMBRE),
    CONSTRAINT FK_COMITE_PARTICIPANT FOREIGN KEY (ID_PART) REFERENCES PARTICIPANT(ID_PART) ON DELETE CASCADE
);

CREATE TABLE COACH (
    ID_COACH INT,
    DIPLOME VARCHAR(255),
    ID_PART INT,
    CONSTRAINT PK_COACH PRIMARY KEY (ID_COACH),
    CONSTRAINT FK_COACH_PARTICIPANT FOREIGN KEY (ID_PART) REFERENCES PARTICIPANT(ID_PART) ON DELETE CASCADE
);

CREATE TABLE ATHLETE (
    ID_ATHLETE INT,
    POIDS DECIMAL(5,2),
    TAILLE DECIMAL(5,2) ,
    ID_COACH INT,
    ID_PART INT,
    CONSTRAINT PK_ATHLETE PRIMARY KEY (ID_ATHLETE),
    CONSTRAINT FK_ATHLETE_COACH FOREIGN KEY (ID_COACH) REFERENCES COACH(ID_COACH) ON DELETE CASCADE,
    CONSTRAINT FK_ATHLETE_PARTICIPANT FOREIGN KEY (ID_PART) REFERENCES PARTICIPANT(ID_PART) ON DELETE CASCADE
);

CREATE TABLE EQUIPE (
    ID_EQUIPE INT,
    NOM_EQUIPE VARCHAR(255),
    ID_COACH INT,
    CONSTRAINT PK_EQUIPE PRIMARY KEY (ID_EQUIPE),
    CONSTRAINT FK_EQUIPE_COACH FOREIGN KEY (ID_COACH) REFERENCES COACH(ID_COACH) ON DELETE CASCADE
);

CREATE TABLE ALLTEAMED (
    ID_EQUIPE INT,
    ID_ATHLETE INT,
    ROLE_TEAM VARCHAR(255),
    CONSTRAINT PK_ALLTEAMED PRIMARY KEY (ID_EQUIPE, ID_ATHLETE),
    CONSTRAINT FK_ALLTEAMED_EQUIPE FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE(ID_EQUIPE) ON DELETE CASCADE,
    CONSTRAINT FK_ALLTEAMED_ATHLETE FOREIGN KEY (ID_ATHLETE) REFERENCES ATHLETE(ID_ATHLETE) ON DELETE CASCADE
);


CREATE TABLE REMPLACE (
    ID_EQUIPE INT,
    ID_ATHLETE1 INT,
    ID_ATHLETE2 INT,
    CONSTRAINT PK_REMPLACE PRIMARY KEY (ID_EQUIPE, ID_ATHLETE1, ID_ATHLETE2),
    CONSTRAINT FK_REMPLACE_EQUIPE FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE(ID_EQUIPE) ON DELETE CASCADE,
    CONSTRAINT FK_REMPLACE_ATHLETE1 FOREIGN KEY (ID_ATHLETE1) REFERENCES ATHLETE(ID_ATHLETE) ON DELETE CASCADE,
    CONSTRAINT FK_REMPLACE_ATHLETE2 FOREIGN KEY (ID_ATHLETE2) REFERENCES ATHLETE(ID_ATHLETE) ON DELETE CASCADE
);

CREATE TABLE CHAMBRE (
    NUM_CHAMBRE INT,
    NB_LITS INT,
    CONSTRAINT PK_CHAMBRE PRIMARY KEY (NUM_CHAMBRE)
);

CREATE TABLE BAIL (
    ID_BAIL INT,
    DATEDEB DATE,
    DATEFIN DATE,
    NUM_CHAMBRE INT,
    CONSTRAINT PK_BAIL PRIMARY KEY (ID_BAIL),
    CONSTRAINT FK_BAIL_CHAMBRE FOREIGN KEY (NUM_CHAMBRE) REFERENCES CHAMBRE(NUM_CHAMBRE) ON DELETE CASCADE
);

CREATE TABLE SIGNE_BAIL (
    ID_BAIL INT,
    ID_PART INT,
    CONSTRAINT PK_SIGNE_BAIL PRIMARY KEY (ID_BAIL, ID_PART),
    CONSTRAINT FK_SIGNE_BAIL_BAIL FOREIGN KEY (ID_BAIL) REFERENCES BAIL(ID_BAIL) ON DELETE CASCADE,
    CONSTRAINT FK_SIGNE_BAIL_PARTICIPANT FOREIGN KEY (ID_PART) REFERENCES PARTICIPANT(ID_PART) ON DELETE CASCADE
);

CREATE TABLE VILLE (
    CODE_POSTAL VARCHAR(5),
    NOM_VILLE VARCHAR(255),
    CONSTRAINT PK_VILLE PRIMARY KEY (CODE_POSTAL)
);

CREATE TABLE PERSONNEL (
    ID_PERS INT,
    TYPE_PERS VARCHAR(255),
    ID_PART INT,
    CONSTRAINT PK_PERSONNEL PRIMARY KEY (ID_PERS),
    CONSTRAINT FK_PERSONNEL_PARTICIPANT FOREIGN KEY (ID_PART) REFERENCES PARTICIPANT(ID_PART) ON DELETE CASCADE
);

CREATE TABLE PERSONNELS_RATTACHES (
    ID_PERS INT,
    CODE_POSTAL VARCHAR(5),
    CONSTRAINT PK_PERSONNELS_RATTACHES PRIMARY KEY (ID_PERS, CODE_POSTAL),
    CONSTRAINT FK_PERSONNELS_RATTACHES_PERSONNEL FOREIGN KEY (ID_PERS) REFERENCES PERSONNEL(ID_PERS) ON DELETE CASCADE,
    CONSTRAINT FK_PERSONNELS_RATTACHES_VILLE FOREIGN KEY (CODE_POSTAL) REFERENCES VILLE(CODE_POSTAL) ON DELETE CASCADE
);

CREATE TABLE CATEGORIE (
    ID_CAT INT,
    NOM_CAT VARCHAR(255),
    GENRE_CAT CHAR(1), -- H ou F
    CONSTRAINT PK_CATEGORIE PRIMARY KEY (ID_CAT)
);

CREATE TABLE DISCIPLINE (
    ID_DISCP INT,
    NOM_DISCP VARCHAR(255),
    ID_CAT INT,
    CONSTRAINT PK_DISCIPLINE PRIMARY KEY (ID_DISCP),
    CONSTRAINT FK_DISCIPLINE_CATEGORIE FOREIGN KEY (ID_CAT) REFERENCES CATEGORIE(ID_CAT) ON DELETE CASCADE
);

CREATE TABLE RECORDS (
    ID_RECORD INT,
    NOM_ATHLETE VARCHAR(255),
    SCORE_RECORD DECIMAL(5,2),
    DATE_RECORD DATE,
    ID_DISCP INT,
    CONSTRAINT PK_RECORDS PRIMARY KEY (ID_RECORD),
    CONSTRAINT FK_RECORDS_DISCIPLINE FOREIGN KEY (ID_DISCP) REFERENCES DISCIPLINE(ID_DISCP) ON DELETE CASCADE
);

CREATE TABLE COMPETITION (
    ID_COMPET INT,
    TYPE_COMPET VARCHAR(255),
    DATE_COMPET DATE,
    HEURE_COMPET TIMESTAMP,
    CODE_POSTAL VARCHAR(5),
    ID_DISCP INT,
    CONSTRAINT PK_COMPETITION PRIMARY KEY (ID_COMPET),
    CONSTRAINT FK_COMPETITION_VILLE FOREIGN KEY (CODE_POSTAL) REFERENCES VILLE(CODE_POSTAL) ON DELETE CASCADE,
    CONSTRAINT FK_COMPETITION_DISCIPLINE FOREIGN KEY (ID_DISCP) REFERENCES DISCIPLINE(ID_DISCP) ON DELETE CASCADE
);

CREATE TABLE EPREUVE (
    ID_COMPET INT,
    NUM_EPREUVE INT,
    TYPE_EPREUVE VARCHAR(255),
    CONSTRAINT PK_EPREUVE PRIMARY KEY (ID_COMPET, NUM_EPREUVE,TYPE_EPREUVE),
    CONSTRAINT FK_EPREUVE_COMPETITION FOREIGN KEY (ID_COMPET) REFERENCES COMPETITION(ID_COMPET) ON DELETE CASCADE
);

CREATE TABLE PARTICIPE (
    ID_PART INT,
    ID_COMPET INT,
    NUM_EPREUVE INT,
    TYPE_EPREUVE VARCHAR(255),
    CONSTRAINT PK_PARTICIPE PRIMARY KEY (ID_PART, ID_COMPET, NUM_EPREUVE,TYPE_EPREUVE),
    CONSTRAINT FK_PARTICIPE_PARTICIPANT FOREIGN KEY (ID_PART) REFERENCES PARTICIPANT(ID_PART) ON DELETE CASCADE,
    CONSTRAINT FK_PARTICIPE_EPREUVE FOREIGN KEY (ID_COMPET, NUM_EPREUVE,TYPE_EPREUVE) REFERENCES EPREUVE(ID_COMPET, NUM_EPREUVE,TYPE_EPREUVE) ON DELETE CASCADE
);

CREATE TABLE PALMARES (
    ID_PAL INT,
    CLASSEMENT INT,
    SCORE_PAL DECIMAL(5,2),
    DATE_PAL DATE,
    ID_DISCP INT,
    ID_ATHLETE INT,
    CONSTRAINT PK_PALMARES PRIMARY KEY (ID_PAL),
    CONSTRAINT FK_PALMARES_DISCIPLINE FOREIGN KEY (ID_DISCP) REFERENCES DISCIPLINE(ID_DISCP) ON DELETE CASCADE,
    CONSTRAINT FK_PALMARES_ATHLETE FOREIGN KEY (ID_ATHLETE) REFERENCES ATHLETE(ID_ATHLETE) ON DELETE CASCADE
);

CREATE TABLE OBTIENT_RESULTATS_ATHLETE (
    ID_ATHLETE INT,
    ID_COMPET INT,
    CLASSEMENT_ATHLETE INT,
    RESULTAT_ATHLETE DECIMAL(5,2) ,
    CONSTRAINT PK_OBTIENT_RESULTATS_ATHLETE PRIMARY KEY (ID_ATHLETE, ID_COMPET),
    CONSTRAINT FK_OBTIENT_RESULTATS_ATHLETE_ATHLETE FOREIGN KEY (ID_ATHLETE) REFERENCES ATHLETE(ID_ATHLETE) ON DELETE CASCADE,
    CONSTRAINT FK_OBTIENT_RESULTATS_ATHLETE_COMPETITION FOREIGN KEY (ID_COMPET) REFERENCES COMPETITION(ID_COMPET) ON DELETE CASCADE
);

CREATE TABLE OBTIENT_RESULTATS_EQUIPE (
    ID_EQUIPE INT,
    ID_COMPET INT,
    CLASSEMENT_EQUIPE INT,
    RESULTAT_EQUIPE DECIMAL(5,2),
    CONSTRAINT PK_OBTIENT_RESULTATS_EQUIPE PRIMARY KEY (ID_EQUIPE, ID_COMPET),
    CONSTRAINT FK_OBTIENT_RESULTATS_EQUIPE_EQUIPE FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPE(ID_EQUIPE) ON DELETE CASCADE,
    CONSTRAINT FK_OBTIENT_RESULTATS_EQUIPE_COMPETITION FOREIGN KEY (ID_COMPET) REFERENCES COMPETITION(ID_COMPET) ON DELETE CASCADE
);

